# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Dimitris Ntounis
email: dntounis@stanford.edu
description: >- 
  PhD Researcher at Stanford University
  Research in Particle Physics and Machine Learning
  Research interests: High Energy Physics, Higgs Boson, Future Colliders, Machine Learning, Data Analysis
author:
  name: Dimitris Ntounis
  bio: PhD Researcher in Particle Physics and Machine Learning at Stanford University
  email: dntounis[AT]stanford[DOT]edu
  institution: Stanford University
  department: Physics
  linkedin_username: dimitris-ntounis-76645b269
  linkedin: dimitris-ntounis-76645b269
  #google_scholar: 5vCzegYAAAAJ
  twitter_username: dimntounis  # if you have one
  twitter: dimntounis  # if you have one
  github_username:  dntounis
  github:  dntounis
  google_scholar: https://scholar.google.com/citations?user=5vCzegYAAAAJ&hl=el
  orcid: 0009-0008-1063-5620

baseurl: "" 
url: "https://dntounis.github.io"

# Avatar (optional)
avatar: /assets/images/IMG_1186_crop.png

# You can add more social links:


#title: Dimitris Ntounis
#email: dntounis@stanford.edu
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _includes

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge




# Scholar settings
scholar:
  style: apa
  locale: en
  sort_by: year,month
  order: descending
  group_by: none
  bibliography_list_tag: ul
  source: _bibliography
  bibliography: references.bib

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/
    permalink: /projects/:title/


# Default layouts
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project



# Navigation
header_pages:
  - projects.md
  - publications.md
  - teaching.md
  - cv.md
#  - about.md
#  - research.md
#  - contact.md

navigation:
  - title: About
    url: /about/
  - title: Research
    url: /research/
    submenu:
      #- title: Current Projects
      #  url: /research/current/
      #- title: Completed Projects
      #  url: /research/completed/
      - title: Current Projects
        url: /projects#current-projects
      - title: Past Projects
        url: /projects#past-projects
  - title: Projects
    url: /projects/
    submenu:
      - title: Current Projects
        url: /projects/current/
      - title: Completed Projects
        url: /projects/completed/
  - title: Publications
    url: /publications/

# Academic Settings
academic_links:
  google_scholar: true
  research_gate: true
  orcid: true    

cv_pdf: /assets/files/Dimitris_Ntounis_academic_CV_November2024.pdf  # Update this path to your CV's location